#!/usr/bin/env node
/**
 * Write git-derived version to src/version.generated.ts for footer.
 * Run via prebuild / predev (npm run build / npm run dev).
 */
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';

let tag = '0.0.0';
let branch = '';
let hash = '';
try {
  // Latest reachable tag
  tag = execSync('git describe --tags --abbrev=0', { encoding: 'utf-8' }).trim();
  branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim();
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch {
  // no git or no commits
}

// Format: "0.1.0-develop-g756be61" or "0.1.0" when on a tagged commit
const isTagged = execSync('git describe --tags --exact-match 2>/dev/null || echo ""', { encoding: 'utf-8' }).trim();
const version = isTagged ? tag : `${tag}-${branch}-${hash}`;

// Short tag for the site title (e.g. "0.1" from "0.1.0")
const shortTag = tag.replace(/\.0$/, '');

const content = `// Generated by scripts/version.mjs — do not edit
export const VERSION = ${JSON.stringify(version)};
export const TAG = ${JSON.stringify(shortTag)};
`;

writeFileSync(new URL('../src/version.generated.ts', import.meta.url), content);

// Also write a .mjs for astro.config.mjs (which can't import .ts)
const configContent = `// Generated by scripts/version.mjs — do not edit
export const TAG = ${JSON.stringify(shortTag)};
`;

writeFileSync(new URL('../src/version.generated.mjs', import.meta.url), configContent);
