#!/usr/bin/env node
/**
 * Write site version to src/version.generated.{ts,mjs}.
 *
 * The lemma-content site version is decoupled from per-study release tags
 * (like `what-is-the-perfect/v5.4`). Those tags don't describe the site as a
 * whole, and letting `git describe --tags` pick them up produces titles like
 * `Lemma vwhat-is-the-perfect/v5.4` which is nonsense.
 *
 * Site version is manual and lives in this file (SITE_VERSION). Bump by
 * editing here + one commit. Rationale for the current value:
 *
 *   v1.0.0 — 2026-08-12 first-live: lemma.gig8.com custom domain live,
 *            15 studies rendered (3 LIVE, 8 DRAFT, 4 PLANNED), first pilot
 *            release cut (what-is-the-perfect v5.4) with reserved Zenodo DOI.
 *
 * Bump policy (semver-lite):
 *   MAJOR  — architecture pivot (new content model, new domain)
 *   MINOR  — meaningful site-wide feature (annotation layer, new landing)
 *   PATCH  — content additions/refinements
 *
 * The build hash (short SHA of HEAD) is appended for build-provenance so
 * "which deploy am I looking at" is answerable from any page's footer.
 */
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';

const SITE_VERSION = '1.1.0';

let hash = '';
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch { /* no git or no commits */ }

// Format:
//   VERSION = "1.0.0-g55cbe4a"   (full — for footer build badge)
//   TAG     = "1.0"              (short — for site title "Lemma v1.0")
const VERSION = hash ? `${SITE_VERSION}-g${hash}` : SITE_VERSION;
const TAG     = SITE_VERSION.replace(/\.0$/, '');

const tsContent = `// Generated by scripts/version.mjs — do not edit
export const VERSION = ${JSON.stringify(VERSION)};
export const TAG = ${JSON.stringify(TAG)};
`;
writeFileSync(new URL('../site/src/version.generated.ts', import.meta.url), tsContent);

const mjsContent = `// Generated by scripts/version.mjs — do not edit
export const TAG = ${JSON.stringify(TAG)};
`;
writeFileSync(new URL('../site/src/version.generated.mjs', import.meta.url), mjsContent);
